# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.srcs/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0.xci
# IP: The module: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/bd_f080.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080 || ORIG_REF_NAME==bd_f080} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/bd_f080_v_hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_hdmi_tx_0 || ORIG_REF_NAME==bd_f080_v_hdmi_tx_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/bd_f080_v_tc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_tc_0 || ORIG_REF_NAME==bd_f080_v_tc_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/bd_f080_v_axi4s_vid_out_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_f080_v_axi4s_vid_out_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_3/bd_f080_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_util_vector_logic_0_0 || ORIG_REF_NAME==bd_f080_util_vector_logic_0_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/bd_f080_axi_crossbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_axi_crossbar_0 || ORIG_REF_NAME==bd_f080_axi_crossbar_0} -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/bd_f080_ooc.xdc

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.srcs/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0.xci
# IP: The module: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/bd_f080.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080 || ORIG_REF_NAME==bd_f080} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/bd_f080_v_hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_hdmi_tx_0 || ORIG_REF_NAME==bd_f080_v_hdmi_tx_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/bd_f080_v_tc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_tc_0 || ORIG_REF_NAME==bd_f080_v_tc_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/bd_f080_v_axi4s_vid_out_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_f080_v_axi4s_vid_out_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_3/bd_f080_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_util_vector_logic_0_0 || ORIG_REF_NAME==bd_f080_util_vector_logic_0_0} -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/bd_f080_axi_crossbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f080_axi_crossbar_0 || ORIG_REF_NAME==bd_f080_axi_crossbar_0} -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/bd_0/bd_f080_ooc.xdc

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_v_hdmi_tx_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
