# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.srcs/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0.xci
# IP: The module: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/synth/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/synth/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.srcs/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0.xci
# IP: The module: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/synth/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/ip_0/synth/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/catmouse/VVAS/ivas-platforms/Embedded/zcu104_vcuDec_vmixHdmiTx/vivado/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1.gen/sources_1/bd/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1/ip/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0/xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zcu104_vcuDec_vmixHdmiTx_202110_1_vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
